<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param Article $article
     */
    public function saveArticle(Article $article)
    {
        $this->getEntityManager()->persist($article);
        $this->getEntityManager()->flush();
    }

    /**
     * @return \AppBundle\Entity\Article[]
     */
    public function findNonDeleted()
    {
        /**
         * @var Article[] $all
         */
        $all = $this->findAll();
        $count = count($all);
        for ($i = 0; $i < $count; $i++) {
            if ($all[$i]->getDeleted()) {
                unset($all[$i]);
            }
        }

        return $all;
    }

    /**
     * @param Article $article
     * @return bool
     */
    public function isArticleUrlUnique(Article $article)
    {
        $countQb = $this->createQueryBuilder('a')
            ->andWhere("a.url = :url")
            ->setParameter('url', $article->getUrl());

        if ($article->getId()) {
            $countQb->andWhere("a.id != :id")
                ->setParameter('id', $article->getId());
        }

        $count = $countQb
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();

        if ($count) {
            return false;
        }

        return true;
    }
}
