<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use AppBundle\Entity\Rubric;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends BaseRepository
{
    public function handleAssociations(&$entity)
    {
        if(method_exists($entity, 'getRubric') && method_exists($entity, 'setRubric') && is_int($entity->getRubric())){
            $entity->setRubric($this->getEm()->getRepository(Rubric::class)->find($entity->getRubric()));
        }
    }

    public function preparePersist(&$entity)
    {
        parent::preparePersist($entity);
        $this->handleAssociations($entity);
    }

    public function findProper(array $query = [])
    {
        $query['andWhere'] = 'a.deleted = 0 AND a.active = 1';
        return $this->query('a', $query);
    }
}
