<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use AppBundle\Entity\Comment;
use Doctrine\ORM\EntityRepository;


/**
 * CommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param Comment $comment
     */
    public function saveComment(Comment $comment)
    {
        $this->getEntityManager()->persist($comment);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Comment $comment
     */
    public function deleteComment(Comment $comment)
    {
        $this->getEntityManager()->remove($comment);
        $this->getEntityManager()->flush();
    }
    
    /**
     * @param $article
     * @param string $orientation
     * @return array
     */
    public function findArticleBaseCommentsOrderedByDate(Article $article, string $orientation = 'DESC') : array
    {
        return $this->createQueryBuilder('c')
            ->where('c.article = :article')
            ->setParameter('article', $article)
            ->andWhere('c.parent IS NULL')
            ->orderBy("c.createdAt", $orientation)
            ->getQuery()
            ->getResult();
    }
}
