<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CommentVote;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * CommentVoteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommentVoteRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param $comment
     * @return array
     */
    public function findByUserAndComment(User $user, $comment)
    {
        $qb = $this->createQueryBuilder('cv')
            ->where('cv.user = :user')
            ->setParameter('user', $user)
            ->andWhere('cv.comment = :comment')
            ->setParameter('comment', $comment);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param CommentVote $commentVote
     */
    public function saveCommentVote(CommentVote $commentVote)
    {
        $this->getEntityManager()->persist($commentVote);
        $this->getEntityManager()->flush();
    }
}
