<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommentRepository extends BaseRepository
{
    /**
     * @param $article
     * @param string $field
     * @param string $orientation
     * @return array
     */
    public function findArticleCommentsOrderedBy($article, $field = 'votes', $orientation = 'DESC')
    {
        return $this->createQueryBuilder('c')
            ->where('c.article = :article')
            ->setParameter('article', $article)
            ->andWhere('c.deleted = false')
            ->orderBy("c.$field", $orientation)
            ->getQuery()->getResult();
    }
}
