app:
    resource: "@AppBundle/Controller/Front/"
    type:     annotation

admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

logout:
    path: /admin/logout

kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor