# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin_logout_success_handler:
        class: AppBundle\Utils\LogoutHandler
        arguments: ["@router", "@security.http_utils", '%admin_logout_target%']

    app.form.rubric_type:
        class: AppBundle\Form\RubricType
        arguments: ['@app.service.rubric_manager']
        tags:
            - { name: form.type, alias: app_bundle_rubric_type }

    app.form.article_type:
        class: AppBundle\Form\ArticleType
        arguments: ['@app.service.rubric_manager']
        tags:
            - { name: form.type, alias: app_bundle_article_type }

    app.form.comment_type:
        class: AppBundle\Form\CommentType
        arguments: ['@router', '@app.service.comment_manager']
        tags:
            - { name: form.type, alias: app_bundle_comment_type }

    app.form.admin_login_type:
        class: AppBundle\Form\AdminLoginType
        tags:
            - { name: form.type, alias: app_bundle_admin_login_type }

    app.form.user_login_type:
        class: AppBundle\Form\UserLoginType
        tags:
            - { name: form.type, alias: app_bundle_user_login_type }

    app.form.user_registration_type:
        class: AppBundle\Form\UserRegistrationType
        tags:
            - { name: form.type, alias: app_bundle_user_registration_type }

    app.service.rubric_manager:
        class: AppBundle\Service\RubricManager
        arguments: ['@doctrine']

    app.service.comment_manager:
        class: AppBundle\Service\CommentManager
        arguments: ['@doctrine']

    app.service.comment_vote_manager:
        class: AppBundle\Service\CommentVoteManager
        arguments: ['@doctrine']

    app.service.article_manager:
        class: AppBundle\Service\ArticleManager
        arguments: ['@doctrine']

    app.service.admin_manager:
        class: AppBundle\Service\AdminManager
        arguments: ['@doctrine', '@security.password_encoder']

    app.service.user_manager:
        class: AppBundle\Service\UserManager
        arguments: ['@doctrine', '@security.password_encoder']

    app.security.admin_login_authenticator:
        class: AppBundle\Security\AdminLoginAuthenticator
        autowire: true

    app.security.user_login_authenticator:
        class: AppBundle\Security\UserLoginAuthenticator
        autowire: true

    app.utils.security_utils:
        class: AppBundle\Utils\SecurityUtils
        arguments: ['@request_stack']